# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean's Portfolio
email: sflaherty09@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 Here is a portfolio of all the projects I have worked on through school and websites I have
 helped design and develop. This will be updated consistently.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: flahertys09
github_username:  sflaherty09

# Build settings
markdown: kramdown
